name: harvesthub_mobile
description: Mobile app for agriculture task management and field monitoring.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  go_router: ^14.2.0
  dio: ^5.7.0
  drift: ^2.18.0
  drift_flutter: ^0.2.0
  sqlite3_flutter_libs: ^0.5.21
  path_provider: ^2.1.4
  path: ^1.9.0
  file_selector: ^1.0.3
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  intl: ^0.19.0
  flex_color_scheme: ^8.0.0
  flutter_colorpicker: ^1.0.3
  shared_preferences: ^2.3.2
  open_filex: ^4.5.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  drift_dev: ^2.18.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo.png
